# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
FROM node:lts-alpine as builder

WORKDIR /app

# Copy package definitions and install all dependencies (including devDependencies) for building
COPY package*.json ./
RUN npm install

# Copy the rest of the application code and build the project
COPY . .
RUN npm run build

# Production stage
FROM node:lts-alpine

WORKDIR /app

# Copy package files (for reference, if needed)
COPY package*.json ./

# Copy production node_modules and built files from the builder stage
COPY --from=builder /app/node_modules ./node_modules
COPY --from=builder /app/dist ./dist

# Expose port if necessary

CMD ["node", "dist/index.js"]
